### ISSUE TITLE
BALL PICKUP - Acquire ball from floor / Stop Acquire ball from floor

### ISSUE THREAD

**Issue by aorouj2049** [feds201/2020_Robot_Code#2]
yeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeet!
started work on jan 29th

STEPS:
1- extend ball intake (& set LED feedback)
2- turn on ball intake
3- turn on ball carousel CCW  (& set LED feedback) might want to turn this on/off separately
4- drive toward ball or receive rolling ball

Once balls are acquired

1- turn off ball intake
2- retract ball intake  (& set LED feedback)
3- after carousel full, stop carousel

New issue - ejecting (if too many balls were picked up)

**Comment by robogirl06** [comment]
Everything but ejecting and LEDs are done.
