### ISSUE TITLE
INDEXER - Carousel - clear a ball jam

### ISSUE THREAD

**Issue by aorouj2049** [feds201/2020_Robot_Code#3]
Yoteeeeeeeeeeeeeeeeeee!
started on jan 29
Assigned to balagi

STEPS:
0- Always set current limit on carousel motor
1- if reach current limit, reverse direction for t ms (maybe 500 ms to start)
2- provide LED feedback on bot
3- pause for t ms (maybe 500 ms to start)
4- continue rotation in intended direction

**Comment by robogirl06** [comment]
Karan added a dither, where indexer rotates forward for 3 sec, backwards for 0.5 sec, which unjams the balls automatically.
