### ISSUE TITLE
CLIMBER - Climb code (with shadows)

### ISSUE THREAD

**Issue by KaranArora1** [feds201/2020_Robot_Code#6]
Started Jan 30
assigned to Arshia, Lucy, Miguel

Climb
0-raise shooter arm (for camera)
1- extend hook (air cylinder?)
2- wait for hook extension
3- drive bot to bar
4- activate winch (to a fixed encoder count)
5- protect for balance drive along bar
6-lower shooter arm to zero position?

**Comment by robogirl06** [comment]
Invert override false
Phase override true
P term = 0.75
Max output = 0.5
Positive output = correct rotation (ratcheting)
20,000 encoder counts is approximately 16" off the ground.

**Comment by robogirl06** [comment]
Changed length of scissor so now winch needs to go to 30,000 encoder counts.
